psql:
    dbname: 'dbname'
    user: 'username'
    host: 'localhost'
    password: ''
    data: '/Users/Username/Downloads/iraq-stats/iraq-stats/ibc-incidents.csv'
    sparkHome: '/Users/Username/Downloads/spark-1.6.2-bin-hadoop2.6'
    sparkClass: '/Users/Username/Downloads/iraq-stats/iraq-stats/postgresql-9.4.1208.jre6.jar'
